export const IPC_CHANNELS = {
  getSnapshot: "dsc:get-snapshot",
  refresh: "dsc:refresh",
  updateLocalConfig: "dsc:update-local-config",
  controlAgent: "dsc:control-agent",
  setAgentSecret: "dsc:set-agent-secret",
  saveHubConnection: "dsc:save-hub-connection",
  login: "dsc:login",
  logout: "dsc:logout",
  cloudPush: "dsc:cloud-push",
  getWidgetLayout: "dsc:get-widget-layout",
  saveWidgetLayout: "dsc:save-widget-layout",
  saveFanNote: "dsc:save-fan-note",
  deleteInstance: "dsc:delete-instance",
  reorderInstances: "dsc:reorder-instances",
  updateStartupSettings: "dsc:update-startup-settings",
  openExternal: "dsc:open-external",
  windowMinimize: "dsc:window-minimize",
  windowToggleMaximize: "dsc:window-toggle-maximize",
  windowClose: "dsc:window-close",
  exit: "dsc:exit",
  snapshot: "dsc:snapshot"
} as const;
